# Generated by Django 3.1.4 on 2022-01-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgupload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='my picture'),
        ),
    ]
